<template><p>This example uses only the required methods to create a shipment and download
its label.</p>
<div class="language-php ext-php"><pre v-pre class="language-php"><code><span class="token variable">$consignment</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token class-name static-context">ConsignmentFactory</span><span class="token operator">::</span><span class="token function">createByCarrierId</span><span class="token punctuation">(</span><span class="token class-name static-context">PostNLConsignment</span><span class="token operator">::</span><span class="token constant">CARRIER_ID</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token operator">-></span><span class="token function">setApiKey</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'api_key_from_backoffice'</span><span class="token punctuation">)</span>
    <span class="token operator">-></span><span class="token function">setReferenceIdentifier</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'order-146'</span><span class="token punctuation">)</span>
    <span class="token operator">-></span><span class="token function">setCountry</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'NL'</span><span class="token punctuation">)</span>
    <span class="token operator">-></span><span class="token function">setPerson</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Piet Hier'</span><span class="token punctuation">)</span>
    <span class="token operator">-></span><span class="token function">setFullStreet</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Plein 1945 55b'</span><span class="token punctuation">)</span>
    <span class="token operator">-></span><span class="token function">setPostalCode</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'2231JE'</span><span class="token punctuation">)</span>
    <span class="token operator">-></span><span class="token function">setCity</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Amsterdam'</span><span class="token punctuation">)</span>
    <span class="token operator">-></span><span class="token function">setEmail</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'piet.hier@test.nl'</span><span class="token punctuation">)</span>
    <span class="token operator">-></span><span class="token function">setLabelDescription</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Order 146'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    
<span class="token variable">$consignments</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">MyParcelCollection</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
    <span class="token operator">-></span><span class="token function">addConsignment</span><span class="token punctuation">(</span><span class="token variable">$consignment</span><span class="token punctuation">)</span>
    <span class="token operator">-></span><span class="token function">setPdfOfLabels</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token variable">$consignmentId</span> <span class="token operator">=</span> <span class="token variable">$consignments</span><span class="token operator">-></span><span class="token function">first</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">getConsignmentId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token variable">$consignments</span><span class="token operator">-></span><span class="token function">downloadPdfOfLabels</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre></div></template>
