version: 2
updates:
  - package-ecosystem: 'github-actions'
    directories:
      - '/'
      - '/.github/actions/*'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'build'
      include: 'scope'
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'build'
      include: 'scope'
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 20
    cooldown:
      exclude:
        - '@myparcel/*'
        - '@myparcel-dev/*'
        - '@myparcel-eslint/*'
        - '@myparcel-pdk/*'
    groups:
      minor-js-updates:
        applies-to: version-updates
        exclude-patterns:
          - "@myparcel-pdk/*"
          - "@myparcel-dev/pdk-*"
        update-types:
          - "minor"
          - "patch"
      js-pdk:
        patterns:
          - '@myparcel-pdk/*'
          - '@myparcel-dev/pdk-*'
