version: 2
registries:
  github:
    type: git
    url: https://github.com/
    username: x-access-token
    password: ${{ secrets.DEPENDABOT_GH_TOKEN }}
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers: ['myparcelnl/integration']

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers: ['myparcelnl/integration']
    versioning-strategy: increase-if-necessary
    groups:
      minor-js-updates:
        applies-to: version-updates
        exclude-patterns:
          - '@myparcel-pdk/*'
        update-types:
          - 'minor'
          - 'patch'
      js-pdk:
        patterns:
          - '@myparcel-pdk/*'
