x-common:
  - &common
    build:
      context: docker
      dockerfile: images/web/Dockerfile
    restart: always
    volumes:
      - ./:/app
      - node-modules:/app/node_modules

services:
  # Usable on https://developer.dev.myparcel.nl/
  web:
    <<: *common
    networks:
      - traefik
    environment:
      TRAEFIK: 1
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik_default
      traefik.port: "8955"
      traefik.frontend.rule: "Host:developer.dev.myparcel.nl"
      traefik.frontend.redirect.entryPoint: 'https'
      traefik.frontend.redirect.permanent: 'true'

  # Usable on http://localhost:8955
  localhost:
    <<: *common
    ports:
      - '8955:8955'

volumes:
  node-modules:

networks:
  traefik:
    name: traefik_default
