import { Vuepress } from '@vuepress/client/lib/components/Vuepress'

const routeItems = [
  ["v-5dc4b15a","/getting-started.html",{"title":"Get started with MyParcel"},["/getting-started","/getting-started.md"]],
  ["v-8daa1a0e","/",{"title":"Go Beyond Delivery with MyParcel."},["/index.html","/readme.md"]],
  ["v-100dc897","/integrations/",{"title":"integrations"},["/integrations/index.html","/integrations/readme.md"]],
  ["v-a4b78024","/documentation/",{"title":"Documentation"},["/documentation/index.html","/documentation/readme.md"]],
  ["v-4f175896","/documentation/14.shopify/02.installatie.html",{"title":"Installation"},["/documentation/14.shopify/02.installatie","/documentation/14.shopify/02.installatie.md"]],
  ["v-f4565a34","/documentation/14.shopify/04.plugin-gebruik.html",{"title":"Plugin gebruik"},["/documentation/14.shopify/04.plugin-gebruik","/documentation/14.shopify/04.plugin-gebruik.md"]],
  ["v-9db00934","/documentation/14.shopify/",{"title":"Introductie"},["/documentation/14.shopify/index.html","/documentation/14.shopify/readme.md"]],
  ["v-1488cdca","/documentation/15.shopware/02.installatie.html",{"title":"Installatie"},["/documentation/15.shopware/02.installatie","/documentation/15.shopware/02.installatie.md"]],
  ["v-a28c6880","/documentation/15.shopware/04.plugin-gebruik.html",{"title":"Plugin gebruik"},["/documentation/15.shopware/04.plugin-gebruik","/documentation/15.shopware/04.plugin-gebruik.md"]],
  ["v-097f13c0","/documentation/15.shopware/",{"title":"Documentation shopware"},["/documentation/15.shopware/index.html","/documentation/15.shopware/readme.md"]],
  ["v-56f52154","/documentation/13.magento2/",{"title":"Introduction"},["/documentation/13.magento2/index.html","/documentation/13.magento2/readme.md"]],
  ["v-16c6f207","/documentation/51.js-sdk/01.installation.html",{"title":"Installation"},["/documentation/51.js-sdk/01.installation","/documentation/51.js-sdk/01.installation.md"]],
  ["v-4783414a","/documentation/51.js-sdk/10.usage-examples.html",{"title":"Usage examples"},["/documentation/51.js-sdk/10.usage-examples","/documentation/51.js-sdk/10.usage-examples.md"]],
  ["v-6cd5c3d4","/documentation/51.js-sdk/20.endpoints.html",{"title":"Endpoints"},["/documentation/51.js-sdk/20.endpoints","/documentation/51.js-sdk/20.endpoints.md"]],
  ["v-aea75c94","/documentation/51.js-sdk/99.contributing.html",{"title":"Contributing"},["/documentation/51.js-sdk/99.contributing","/documentation/51.js-sdk/99.contributing.md"]],
  ["v-1b75a356","/documentation/51.js-sdk/",{"title":"Introduction"},["/documentation/51.js-sdk/index.html","/documentation/51.js-sdk/readme.md"]],
  ["v-990f7b3e","/documentation/50.php-sdk/01.installation.html",{"title":"Installation"},["/documentation/50.php-sdk/01.installation","/documentation/50.php-sdk/01.installation.md"]],
  ["v-21b7a55b","/documentation/50.php-sdk/05.exceptions.html",{"title":"Exceptions"},["/documentation/50.php-sdk/05.exceptions","/documentation/50.php-sdk/05.exceptions.md"]],
  ["v-366a4830","/documentation/50.php-sdk/06.tips.html",{"title":"Tips"},["/documentation/50.php-sdk/06.tips","/documentation/50.php-sdk/06.tips.md"]],
  ["v-031d8694","/documentation/50.php-sdk/07.contribute.html",{"title":"Contribute"},["/documentation/50.php-sdk/07.contribute","/documentation/50.php-sdk/07.contribute.md"]],
  ["v-0c0aa0a2","/documentation/50.php-sdk/",{"title":"Introduction"},["/documentation/50.php-sdk/index.html","/documentation/50.php-sdk/readme.md"]],
  ["v-748b67f0","/documentation/20.wix/02.installatie.html",{"title":"Installatie"},["/documentation/20.wix/02.installatie","/documentation/20.wix/02.installatie.md"]],
  ["v-30dfde6a","/documentation/20.wix/04.plugin-gebruik.html",{"title":"Plugin gebruik"},["/documentation/20.wix/04.plugin-gebruik","/documentation/20.wix/04.plugin-gebruik.md"]],
  ["v-18deb30b","/documentation/20.wix/",{"title":"Inleiding"},["/documentation/20.wix/index.html","/documentation/20.wix/readme.md"]],
  ["v-936ad046","/documentation/14.shopify/03.configuratie/01.account.html",{"title":"Account"},["/documentation/14.shopify/03.configuratie/01.account","/documentation/14.shopify/03.configuratie/01.account.md"]],
  ["v-0b64a4c8","/documentation/14.shopify/03.configuratie/02.algemene-instellingen.html",{"title":"Algemene instellingen"},["/documentation/14.shopify/03.configuratie/02.algemene-instellingen","/documentation/14.shopify/03.configuratie/02.algemene-instellingen.md"]],
  ["v-c5431076","/documentation/14.shopify/03.configuratie/03.standaard-exportinstellingen.html",{"title":"Standaard exportinstellingen"},["/documentation/14.shopify/03.configuratie/03.standaard-exportinstellingen","/documentation/14.shopify/03.configuratie/03.standaard-exportinstellingen.md"]],
  ["v-0c8952ae","/documentation/14.shopify/03.configuratie/04.herinneringsmail-afhaallocatie.html",{"title":"Herinneringsmail afhaallocatie"},["/documentation/14.shopify/03.configuratie/04.herinneringsmail-afhaallocatie","/documentation/14.shopify/03.configuratie/04.herinneringsmail-afhaallocatie.md"]],
  ["v-464c53d6","/documentation/14.shopify/03.configuratie/05.wereldzendingen.html",{"title":"Wereldzendingen"},["/documentation/14.shopify/03.configuratie/05.wereldzendingen","/documentation/14.shopify/03.configuratie/05.wereldzendingen.md"]],
  ["v-714b27da","/documentation/14.shopify/03.configuratie/06.veelgestelde-vragen-over-de-configuratie.html",{"title":"Veelgestelde vragen over de configuratie"},["/documentation/14.shopify/03.configuratie/06.veelgestelde-vragen-over-de-configuratie","/documentation/14.shopify/03.configuratie/06.veelgestelde-vragen-over-de-configuratie.md"]],
  ["v-f0c2edfa","/documentation/15.shopware/03.configuratie/01.api-instellingen.html",{"title":"API instellingen"},["/documentation/15.shopware/03.configuratie/01.api-instellingen","/documentation/15.shopware/03.configuratie/01.api-instellingen.md"]],
  ["v-575a78fa","/documentation/15.shopware/03.configuratie/02.toon-pickup-punten-bij-afrekenen.html",{"title":"Toon pickup punten bij afrekenen"},["/documentation/15.shopware/03.configuratie/02.toon-pickup-punten-bij-afrekenen","/documentation/15.shopware/03.configuratie/02.toon-pickup-punten-bij-afrekenen.md"]],
  ["v-3cff1731","/documentation/15.shopware/03.configuratie/03.standaard-afleveringsperiode.html",{"title":"Standaard afleveringsperiode"},["/documentation/15.shopware/03.configuratie/03.standaard-afleveringsperiode","/documentation/15.shopware/03.configuratie/03.standaard-afleveringsperiode.md"]],
  ["v-08d7c498","/documentation/15.shopware/03.configuratie/04.standaard-handtekening-bij-bezorging.html",{"title":"Standaard handtekening bij bezorging"},["/documentation/15.shopware/03.configuratie/04.standaard-handtekening-bij-bezorging","/documentation/15.shopware/03.configuratie/04.standaard-handtekening-bij-bezorging.md"]],
  ["v-327c4b5a","/documentation/15.shopware/03.configuratie/05.standaard-aflevering-bij-buren.html",{"title":"Standaard aflevering bij buren"},["/documentation/15.shopware/03.configuratie/05.standaard-aflevering-bij-buren","/documentation/15.shopware/03.configuratie/05.standaard-aflevering-bij-buren.md"]],
  ["v-59f63d76","/documentation/15.shopware/03.configuratie/06.retour-bij-geen-gehoor.html",{"title":"Stuur standaard het pakket terug naar de afzender als de ontvanger niet thuis is (Retour bij geen gehoor)"},["/documentation/15.shopware/03.configuratie/06.retour-bij-geen-gehoor","/documentation/15.shopware/03.configuratie/06.retour-bij-geen-gehoor.md"]],
  ["v-204b9118","/documentation/15.shopware/03.configuratie/07.leeftijdscontrole.html",{"title":"De klant welke voor het pakket tekent dient minstens 18 jaar te zijn"},["/documentation/15.shopware/03.configuratie/07.leeftijdscontrole","/documentation/15.shopware/03.configuratie/07.leeftijdscontrole.md"]],
  ["v-3c6738f4","/documentation/15.shopware/03.configuratie/08.standaard-verpakkingssoort.html",{"title":"Standaard verpakkingssoort"},["/documentation/15.shopware/03.configuratie/08.standaard-verpakkingssoort","/documentation/15.shopware/03.configuratie/08.standaard-verpakkingssoort.md"]],
  ["v-2b18e6aa","/documentation/15.shopware/03.configuratie/09.toon-ochtend-levering.html",{"title":"Toon ochtend levering"},["/documentation/15.shopware/03.configuratie/09.toon-ochtend-levering","/documentation/15.shopware/03.configuratie/09.toon-ochtend-levering.md"]],
  ["v-532cfaaa","/documentation/15.shopware/03.configuratie/10.toon-avond-levering.html",{"title":"Toon avond levering"},["/documentation/15.shopware/03.configuratie/10.toon-avond-levering","/documentation/15.shopware/03.configuratie/10.toon-avond-levering.md"]],
  ["v-1c943a46","/documentation/15.shopware/03.configuratie/11.standaard-verzendwijze.html",{"title":"Standaard verzendwijze"},["/documentation/15.shopware/03.configuratie/11.standaard-verzendwijze","/documentation/15.shopware/03.configuratie/11.standaard-verzendwijze.md"]],
  ["v-5de2f53d","/documentation/15.shopware/03.configuratie/12.label-instellingen.html",{"title":"Label instellingen"},["/documentation/15.shopware/03.configuratie/12.label-instellingen","/documentation/15.shopware/03.configuratie/12.label-instellingen.md"]],
  ["v-49796ea9","/documentation/50.php-sdk/02.examples/01.create-consignment.html",{"title":"Create a consignment"},["/documentation/50.php-sdk/02.examples/01.create-consignment","/documentation/50.php-sdk/02.examples/01.create-consignment.md"]],
  ["v-6b0f79ad","/documentation/50.php-sdk/02.examples/02.using-multiple-carriers.html",{"title":"Using multiple carriers"},["/documentation/50.php-sdk/02.examples/02.using-multiple-carriers","/documentation/50.php-sdk/02.examples/02.using-multiple-carriers.md"]],
  ["v-fa28b196","/documentation/50.php-sdk/02.examples/03.create-multiple-consignments.html",{"title":"Create multiple consignments"},["/documentation/50.php-sdk/02.examples/03.create-multiple-consignments","/documentation/50.php-sdk/02.examples/03.create-multiple-consignments.md"]],
  ["v-cd9220b6","/documentation/50.php-sdk/02.examples/04.create-return-in-the-box.html",{"title":"Create return in the box"},["/documentation/50.php-sdk/02.examples/04.create-return-in-the-box","/documentation/50.php-sdk/02.examples/04.create-return-in-the-box.md"]],
  ["v-7fd6611d","/documentation/50.php-sdk/02.examples/05.label-format-and-position.html",{"title":"Label format and position"},["/documentation/50.php-sdk/02.examples/05.label-format-and-position","/documentation/50.php-sdk/02.examples/05.label-format-and-position.md"]],
  ["v-7c577f04","/documentation/50.php-sdk/02.examples/06.package-type-and-options.html",{"title":"Package types and options"},["/documentation/50.php-sdk/02.examples/06.package-type-and-options","/documentation/50.php-sdk/02.examples/06.package-type-and-options.md"]],
  ["v-375dbe2d","/documentation/50.php-sdk/02.examples/07.find-consignments.html",{"title":"Find consignments"},["/documentation/50.php-sdk/02.examples/07.find-consignments","/documentation/50.php-sdk/02.examples/07.find-consignments.md"]],
  ["v-d961d1fe","/documentation/50.php-sdk/02.examples/08.query-consignments.html",{"title":"Query consignments"},["/documentation/50.php-sdk/02.examples/08.query-consignments","/documentation/50.php-sdk/02.examples/08.query-consignments.md"]],
  ["v-ff3eb686","/documentation/50.php-sdk/02.examples/09.retrieve-data-from-a-consignment.html",{"title":"Retrieve data from a consignment"},["/documentation/50.php-sdk/02.examples/09.retrieve-data-from-a-consignment","/documentation/50.php-sdk/02.examples/09.retrieve-data-from-a-consignment.md"]],
  ["v-6e141b96","/documentation/50.php-sdk/02.examples/10.create-and-download-labels.html",{"title":"Create and download label(s)"},["/documentation/50.php-sdk/02.examples/10.create-and-download-labels","/documentation/50.php-sdk/02.examples/10.create-and-download-labels.md"]],
  ["v-42374bcf","/documentation/50.php-sdk/02.examples/11.orders.html",{"title":"Create and save orders"},["/documentation/50.php-sdk/02.examples/11.orders","/documentation/50.php-sdk/02.examples/11.orders.md"]],
  ["v-06b11005","/documentation/50.php-sdk/02.examples/12.instabox.html",{"title":"Filling in required drop-off point for Instabox"},["/documentation/50.php-sdk/02.examples/12.instabox","/documentation/50.php-sdk/02.examples/12.instabox.md"]],
  ["v-55e309fa","/documentation/50.php-sdk/02.examples/13.webhooks.html",{"title":"Setting up webhooks"},["/documentation/50.php-sdk/02.examples/13.webhooks","/documentation/50.php-sdk/02.examples/13.webhooks.md"]],
  ["v-2dbb7402","/documentation/50.php-sdk/03.reference/01.models.html",{"title":"Models"},["/documentation/50.php-sdk/03.reference/01.models","/documentation/50.php-sdk/03.reference/01.models.md"]],
  ["v-4841a3c0","/documentation/50.php-sdk/03.reference/02.helpers.html",{"title":"Helpers"},["/documentation/50.php-sdk/03.reference/02.helpers","/documentation/50.php-sdk/03.reference/02.helpers.md"]],
  ["v-4b8f576e","/documentation/50.php-sdk/03.reference/03.delivery-options.html",{"title":"Delivery options from the checkout with adapters"},["/documentation/50.php-sdk/03.reference/03.delivery-options","/documentation/50.php-sdk/03.reference/03.delivery-options.md"]],
  ["v-38e2745e","/documentation/20.wix/03.configuratie/01.pakketvoorkeuren.html",{"title":"Pakketvoorkeuren"},["/documentation/20.wix/03.configuratie/01.pakketvoorkeuren","/documentation/20.wix/03.configuratie/01.pakketvoorkeuren.md"]],
  ["v-4e499e7b","/documentation/20.wix/03.configuratie/02.veelgestelde-vragen-over-de-configuratie.html",{"title":"Veelgestelde vragen over de configuratie"},["/documentation/20.wix/03.configuratie/02.veelgestelde-vragen-over-de-configuratie","/documentation/20.wix/03.configuratie/02.veelgestelde-vragen-over-de-configuratie.md"]],
  ["v-6092ecaa","/documentation/13.magento2/03.configuratie/01.configuratie.html",{"title":"Configuratie"},["/documentation/13.magento2/03.configuratie/01.configuratie","/documentation/13.magento2/03.configuratie/01.configuratie.md"]],
  ["v-604a5250","/documentation/13.magento2/03.configuratie/02.algemene-instellingen.html",{"title":"Algemene instellingen"},["/documentation/13.magento2/03.configuratie/02.algemene-instellingen","/documentation/13.magento2/03.configuratie/02.algemene-instellingen.md"]],
  ["v-69fd3c26","/documentation/13.magento2/03.configuratie/03.standaard-verzendinstellingen.html",{"title":"Standaard verzendinstellingen"},["/documentation/13.magento2/03.configuratie/03.standaard-verzendinstellingen","/documentation/13.magento2/03.configuratie/03.standaard-verzendinstellingen.md"]],
  ["v-0a95fc45","/documentation/13.magento2/03.configuratie/04.backend-functionaliteiten.html",{"title":"Backend functionaliteiten"},["/documentation/13.magento2/03.configuratie/04.backend-functionaliteiten","/documentation/13.magento2/03.configuratie/04.backend-functionaliteiten.md"]],
  ["v-47a070ba","/documentation/13.magento2/03.configuratie/05.checkout-instellingen.html",{"title":"Checkout instellingen"},["/documentation/13.magento2/03.configuratie/05.checkout-instellingen","/documentation/13.magento2/03.configuratie/05.checkout-instellingen.md"]],
  ["v-02f66c5a","/documentation/13.magento2/03.configuratie/06.veelgestelde-vragen.html",{"title":"Veel gestelde vragen"},["/documentation/13.magento2/03.configuratie/06.veelgestelde-vragen","/documentation/13.magento2/03.configuratie/06.veelgestelde-vragen.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
]

export const pagesRoutes = routeItems.reduce(
  (result, [name, path, meta, redirects]) => {
    result.push(
      {
        name,
        path,
        component: Vuepress,
        meta,
      },
      ...redirects.map((item) => ({
        path: item,
        redirect: path,
      }))
    )
    return result
  },
  [
    {
      name: "404",
      path: "/:catchAll(.*)",
      component: Vuepress,
    }
  ]
)
