name: 'Check pull request'

on: pull_request

jobs:
  build:
    name: 'Test site build'
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.event.client_payload.pull_request.head.ref }}
