name: '🧪 Run tests'

on:
  pull_request:

  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - uses: ./.github/actions/build

      - name: 'Test links'
        run: |
          yarn test:links
